steps:
- name: gcr.io/cloud-builders/bazel
  args: [
    'build', 
    '--spawn_strategy=remote',
    '--remote_rest_cache=https://bazelcas.herokuapp.com/',
    '--strategy=Javac=remote',
    '--strategy=Closure=remote',
    '//srv',
  ]

timeout: 1800s
